---
functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте.
  - Пользователь должен иметь возможность залогиниться и отлогиниться на сайте.
  - Пользователь должен иметь возможность просматривать поединок идущий в лобби.
  - Пользователь должен иметь возможность создать поединок с другим пользователем/другом/ботом.
  - Пользователь должен иметь возможность проматривать статистику по поединкам, чемпионатам и игрокам.
  - Пользователь должен иметь возможность просматривать свой профиль и информацию по нему.
  - Пользователь должен иметь возможность писать в чат в лобби.
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь удобную мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров на PC и мобильных устройствах.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Сайт должен быть протестирован на совместимость с предпоследними версиями браузеров на PC.
  - Сайт должен быть протестирован на совместимость с последними и предпоследними версиями браузеров на мобильных устройствах с IOS и AndrPoid.
  - Компьютер, на котором расположен сайт, должен иметь железо и подключение к сети, способное поддерживать большое количество трафика и безперебойное соединение.
  - Пользователь должен иметь возможность успешно перейти по ссылкам на сторонние ресурсы, ссылки на которые представлены на сайте.
  - Пользователь должен иметь возможность просматривать статистику любого пользователя.
  - Пользователь должен иметь доступ к возможным настройкам в своем профиле.